let namesFind = [{
    isPopular: true, 
    src: "picturestravel/France.png",
    heading: 'Париж',
    description: '9 дней | 12 дней  поездка в Нормандию и Париж',
    price: '138 000 руб.',
    oldPrice: '150 000 руб',
    button: 'Выбрать',
    id: 1,
},
{
    isPopular: true, 
    src: "picturestravel/Italy.png",
    heading: 'Италия, Манарола',
    description: '12 дней | 14 дней с поездкой в Рим',
    price: '175 000 руб.',
    oldPrice: '190 000 руб',
    button: 'Выбрать',
    id: 2,
},
{
    isPopular: true, 
    src: "picturestravel/Rome.png",
    heading: 'Италия, Рим',
    description: '11 дней | 14 дней с поездкой в Мадрид',
    price: '200 000 руб.',
    oldPrice: '230 000 руб',
    button: 'Выбрать',
    id: 3,
},
{
    isPopular: false, 
    src: "picturestravel/Venice.png",
    heading: 'Италия, Венеция',
    description: '9 дней | 11 дней с поездкой на полуостров Сорренто',
    price: '155 000 руб.',
    oldPrice: '177 000 руб',
    button: 'Выбрать',
    id: 4,
},
{
    isPopular: false, 
    src: "picturestravel/Spain.png",
    heading: 'Тур по Испании',
    description: '14 дней | 16 дней с поездкой в Барселону',
    price: '200 000 руб.',
    oldPrice: '210 000 руб',
    button: 'Выбрать',
    id: 5,  
},
{
    isPopular: false, 
    src: "picturestravel/Brazil.png",
    heading: 'Бразилия, Рио',
    description: 'Рио, водопады Игуасу и Буэнос-Айрес',
    price: '225 000 руб.',
    oldPrice: '240 000 руб',
    button: 'Выбрать',
    id: 6,  
},
{
    isPopular: false, 
    src: "picturestravel/Helsinki.png",
    heading: 'Хельсинки',
    description: 'Скандинавия: столицы и фьорды',
    price: '215 000 руб.',
    oldPrice: '230 000 руб',
    button: 'Выбрать',
    id: 7,  
},
{
    isPopular: false, 
    src: "picturestravel/London.png",
    heading: 'Лондон',
    description: '9 дней | 11 дней с поездкой в Париж',
    price: '285 000 руб.',
    oldPrice: '295 000 руб',
    button: 'Выбрать',
    id: 8,  
},
{
    isPopular: false, 
    src: "picturestravel/Alaska.png",
    heading: 'Аляска',
    description: 'Национальный парк Денали и круиз по дикой Аляске',
    price: '300 000 руб.',
    oldPrice: '310 000 руб',
    button: 'Выбрать',
    id: 9,  
}
]